### ISSUE TITLE
Some sub-messages are always updated for next message

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opamp-go#108]
👋 , I have been trying to get familiar with the spec and the current implementation. There is a [section](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agent-status-compression) about agent status compression which says sub-messages can be omitted in case of no change and the client implementation does it only for `RemoteConfigStatus` and `PackageStatuses` not for the `EffectiveConfig`, `AgentHealth` and `AgentDescription`. I was wondering if there was reason behind this?

**Comment by tigrannajaryan** [comment]
>the client implementation does it only for RemoteConfigStatus and PackageStatuses not for the EffectiveConfig, AgentHealth and AgentDescription. I was wondering if there was reason behind this?

The client implementation compresses all these messages. See NextMessage.PopPending implementation. Once the message is popped and sent these fields are unset and will be only set in the next message if they are modified via NextMessage.Update.

**Comment by srikanthccv** [comment]
Thanks, that was helpful. I think my original question should have been more clear. Should the client push update to NextMessage even if there was no change and schedule send.

I am looking at this implementation b/w SetAgentDescription and SetRemoteConfigStatus.
https://github.com/open-telemetry/opamp-go/blob/63c9165ebef63cde0c6e8ddff0513b38e9e2a8b8/client/internal/clientcommon.go#L226-L241
https://github.com/open-telemetry/opamp-go/blob/63c9165ebef63cde0c6e8ddff0513b38e9e2a8b8/client/internal/clientcommon.go#L289-L314

**Comment by tigrannajaryan** [comment]
> Should the client push update to NextMessage even if there was no change and schedule send.

Do you mean the situation when for example `SetRemoteConfigStatus` is called with a `descr` parameter that is equal to the current `c.ClientSyncedState.AgentDescription()`? You are right that in this case a message will be sent to the Server when with `AgentDescription` field set when actually the field could have been omitted. We can make a deep comparison and avoid sending it, but the Server should be ready for this to happen anyway, so this should not result in any erroneous situation, it will be just unnecessary data sent.

**Comment by srikanthccv** [comment]
Thanks for the clarification.
