### ISSUE TITLE
Websocket Race Condition when closing

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opamp-go#111]
There appears to be a race condition when calling `Stop()` on a websocket client. 

The [runUntilStopped](https://github.com/open-telemetry/opamp-go/blob/main/client/wsclient.go#L256-L265) function checks `IsStopping()` before `runOneCycle`. Inside `runOneCycle` we attempt to connect via [ensureConnected](https://github.com/open-telemetry/opamp-go/blob/main/client/wsclient.go#L200) then check `IsStopping()` again. The race condition lies in if `Stop()` is called on the client after the first `IsStopping()` check in `runUntilStopped` but before the second one in `runOneCycle`. 

If this happens `ensureConnected` could possible fail due to a closed connection. Which is looks like we account for in [this](https://github.com/open-telemetry/opamp-go/blob/main/client/wsclient.go#L201-L203) comment. The problem is on a failed connection the `OnConnectFailedHandler` is called and could execute any code associated with that on the implementors side. This is not ideal in a graceful shutdown.

I'm wondering if it's a better idea to swap the `IsStopping()` check and `ensureConnected` inside `runOnceCycle`. This way we don't try to connect if we're currently stopping.

```go
	if c.common.IsStopping() {
		_ = c.conn.Close()
		return
	}

	if err := c.ensureConnected(ctx); err != nil {
                // Maybe log error here
		return
	}
```

**Comment by tigrannajaryan** [comment]
>I'm wondering if it's a better idea to swap the IsStopping() check and ensureConnected inside runOnceCycle.

I don't think this will fix the problem. Stop() can be called after IsStopping() check and we will be back to the same situation.

I think the fix is to check if `isStopping()==true` then don't call `OnConnectFailed`.

@cpheps  Would you be able to write a test that triggers this race condition and then we see if my proposed fix works?

**Comment by cpheps** [comment]
@tigrannajaryan Yeah good call on the proposed fix. I'll test it out in the environment we're seeing the race condition. Seem like it happens every time so should be able to tell if that fix works.

**Comment by cpheps** [comment]
@tigrannajaryan that looks like it worked I'll throw up a PR to fix it.
