### ISSUE TITLE
retry policy: parse datetime value for Retry-After header?

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opamp-go#119]
I started working on writing tests as part of #99. I noticed that the retry header only works with delay [seconds](https://github.com/open-telemetry/opamp-go/blob/main/internal/retryafter.go#L26). The header value can either be seconds or datatime. Should the datetime case be accounted for or assume the server always sends the seconds?

**Comment by tigrannajaryan** [comment]
I think yes, we should allow datetime since HTTP spec allows that.

**Comment by nemoshlag** [comment]
Hi 👋 would like to help with this one if needed

**Comment by tigrannajaryan** [comment]
@nemoshlag sounds great, I assigned this issue to you.
