### ISSUE TITLE
Prototype a Supervisor

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-go#12]
We want to create a prototype of a Supervisor. See initial thoughts https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit#

Likely some of the capabilities will require changes in the Collector. Doing the prototyping will help us understand what should go in the Supervisor and what goes into the Collector.

Task List:
- [x] https://github.com/open-telemetry/opamp-go/issues/23
- [x] https://github.com/open-telemetry/opamp-go/issues/24
- [x] https://github.com/open-telemetry/opamp-go/issues/25

**Comment by tigrannajaryan** [comment]
It would be good to put together a small design doc that explains how the supervisor will work, what its own configuration file will look like, how it will interact with the Collector.

Ideally we want to make the Supervisor a reusable go library, instead of hard-coding it to be specific to Otel Collector only. The library then can be probably used to create 2 Supervisor executables: one generic that works for any agent (assuming the Supervisor knows where the Agent executable is and where the config file is) and possibly a second, more specific one tailored to the Collector (if we need it to be specific in any way). We don't need to do this all in the prototype but it would be useful to keep this goal in mind.

**Comment by kart** [comment]
Can you provide some example agents (other than OTEL collector) that fits the bill for being managed by a generic supervisor? Any generic daemon-like process that has an underlying configuration file and therefore can be managed by the supervisor?

**Comment by tigrannajaryan** [comment]
Yes, presumably any agent that is a standalone executable and has a notion of a config file can be managed (perhaps in a limited way) by the generic Supervisor. For example Fluentbit.

**Comment by kart** [comment]
Can a single OpAMP server manage multiple agent types (OTEL collector, Fluentbit, etc) or are we envisioning it to manage multiple? I suspect the latter. I ask because the client implementation (specifically, StartSettings.AgentType ) in the repo seems to suggest a 1:1 mapping between an agent type and OpAMP server.

**Comment by tigrannajaryan** [comment]
OpAMP Server should be able to manage multiple agent types. Nothing in the protocol prevents that, the protocol is designed to work for that use case.

The Client implementation is for a single Agent, but there can be multiple Agents, each with its own Client, each using a different Agent type. There is 1:1 mapping between Agent and Client. There is no 1:1 mapping between Agent type and OpAMP Server.

**Comment by tigrannajaryan** [comment]
Closing, prototyping is done. Collector supervisor prototype is created: https://github.com/open-telemetry/opamp-go/tree/main/internal/examples/supervisor
