### ISSUE TITLE
Supervisor example crushes agent

### ISSUE THREAD

**Issue by nemoshlag** [open-telemetry/opamp-go#128]
Hi, it seems that the localOverrideAgentConfigs defined at https://github.com/open-telemetry/opamp-go/blob/89eeb30c8d70e54aef663c17b764455e4d053bc8/internal/examples/supervisor/supervisor/supervisor.go#L33 causing agent to flicker:
`2022/09/05 11:30:19 Agent process started, PID=17633
2022/09/05 11:30:20 Agent process PID=17633 exited unexpectedly, exit code=1. Will restart in a bit...
2022/09/05 11:30:25 Starting agent /Users/nemos/Dev/SDK/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64
2022/09/05 11:30:25 Agent process started, PID=17636
2022/09/05 11:30:25 Agent process PID=17636 exited unexpectedly, exit code=1. Will restart in a bit...
`
Attaching a PR for a suggested fix to initial agent configurations and print effective configuration to debug log in case of agent shutdown on https://github.com/open-telemetry/opamp-go/pull/127

**Comment by tigrannajaryan** [comment]
I am unable to reproduce this. Do you use the example Server or something else? What is the Agent's effective config (it should be written to `effective.yaml` file)? What does Agent's log show? Why is it crashing?

**Comment by nemoshlag** [comment]
Hmm, this appeared to be my bad, can't replicate it either. I guess I had a server running with bad configurations causing the agent to flicker, thanks
