### ISSUE TITLE
Improved logging interface

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opamp-go#154]
Right now the types.Logger interface only has two methods `DebugF` and `Errorf` with the same signature `format string, v ...interface{}`. This makes it difficult to incorporate custom loggers which may expect `err` as the first parameter.

**Comment by tigrannajaryan** [comment]
You can wrap a logger and implement this interface. Let me know if this is still necessary, if not I will close the issue.

**Comment by jaronoff97** [comment]
@tigrannajaryan I'm coming back to this now with a similar issue. I'm wondering if we could add new methods that allow for the propagation of context. This would be similar to the [slog](https://pkg.go.dev/golang.org/x/exp/slog#hdr-Contexts) package which allows consumers to supply a context when they would like to propagate it. I'll work on a PR to prototype this.
