### ISSUE TITLE
OPAMP Client with Otel Agent support w/o supervisor

### ISSUE THREAD

**Issue by sumanthculli** [open-telemetry/opamp-go#165]
1)  The documentation https://opentelemetry.io/docs/collector/management/  states that opAMP control flow between the control plane implementing the server-side OpAMP part and the collector (or a supervisor controlling the collector) implementing OpAMP client-side, if there is more documentation around using OPAMP server  without the supervisor by including the OPAMP client in the otel collector( agent) will also help.

Thank you.

**Comment by tigrannajaryan** [comment]
This is work-in-progress in Collector. Feel free to comment here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16462
