### ISSUE TITLE
Provide more flexibility for PackagesStateProvider for error 

### ISSUE THREAD

**Issue by phanidevavarapu** [open-telemetry/opamp-go#175]
During the package UpdateContent in the package syncer, the error is wrapped, instead please provide more flexibility for the PackagesStateProvider implementer for error to throw. 
This will help code the service to determine the types of errors internally.   

Note: The error message itself is wrong in this case. 
https://github.com/open-telemetry/opamp-go/blob/main/client/internal/packagessyncer.go#L279-L282

**Comment by tigrannajaryan** [comment]
This needs more details. It is unclear what exactly the problem is and the goal is.
