### ISSUE TITLE
TestAgentIdentification/ws is flaky

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-go#191]
See https://github.com/open-telemetry/opamp-go/actions/runs/5487663480/jobs/9999430522

I can sometimes reproduce this locally by doing `go test -run TestAgentIdentification/ws -race -count 1000`

**Comment by srikanthccv** [comment]
Another case https://github.com/open-telemetry/opamp-go/actions/runs/6248732304/job/16963976273

**Comment by tigrannajaryan** [comment]
Failed again: https://github.com/open-telemetry/opamp-go/actions/runs/6551109455/job/17791657822?pr=207

**Comment by tpaschalis** [comment]
I couldn't reproduce any failures even after >40k tries with `$ go test -run TestAgentIdentification/ws -race -count 10000 ./...`. Also, these old action runs no longer have any logs associated with them.

The TestAgentIdentification case has been made more realistic after #286 and seems stable, so do we think it'd be a good idea to close this issue out?

**Comment by tigrannajaryan** [comment]
Sounds good to me, let's close. We will reopen if we see the failure again.
