### ISSUE TITLE
Move certs helper code from /internal/examples to /internal or /internal/testhelper?

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opamp-go#199]
In an effort to improve the test coverage for [serverimpl](https://app.codecov.io/gh/open-telemetry/opamp-go/blob/main/server%2Fserverimpl.go), I started to add some tests with TLS enabled. I noticed we already have some useful code for generating and reading certs in `internal/examples/...`, and it seems like a good idea to use for tests. I was thinking of moving them to `/internal` or maybe `internal/testhelper` and use in both serverimpl tests and examples.

@tigrannajaryan do you see any issues with this? If not, I can send a PR for this along with the new serverimpl TLS tests.

**Comment by tigrannajaryan** [comment]
Sounds good to me.
