### ISSUE TITLE
Design Supervisor library API

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-go#23]
Design the API of the Go library that can be used to implement supervisors.

**Comment by kart** [comment]
I'll take this up and produce a basic structural interface on which other things can be built. Going to assume a simple configuration to help bootstrap this.

**Comment by tigrannajaryan** [comment]
@kart thanks. Please post the design as a draft PR in this repo when you have it.

**Comment by tigrannajaryan** [comment]
Closing this for now. I do not think this should be a current goal, instead we will be a Collector-specific Supervisor. We may reopen this in the future.
