### ISSUE TITLE
Decide on directory structure

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-go#4]
Here is a possible directory structure:

- client - for client-side OpAMP implementation, package importable by agents that want to adopt OpAMP.
- server - for server-side OpAMP implementation, package important by vendors who want to implement OpAMP servers.
- internal - shared internal code for client and server (e.g. protobufs).
- examples - examples that use client and server packages.

Questions:
1. Do we put client and server under pkg or top-level is fine?
2. Does everything use one top-level go.mod or client and server use their own go.mod (typically you only use one in a particular executable, both are only necessary if you building a proxy of some sort).
3. I think we also want a prototype implementation of the Supervisor in this repo. Where do we put it? Does it go into the examples or somewhere in cmd/supervisor?

**Comment by tigrannajaryan** [comment]
@open-telemetry/opamp-go-approvers please comment.

**Comment by tigrannajaryan** [comment]
@open-telemetry/opamp-go-approvers @open-telemetry/opamp-go-maintainers  please comment.

**Comment by djaglowski** [comment]
I think the proposed structure is a good starting point.
1. We can align with the collector repo by omitting the `pkg` directory.
2. Keep it simple until a clear need for multiple modules is articulated?
3. `cmd/supervisor` seems right to me.

**Comment by Aneurysm9** [comment]
Mostly agree with what Dan said.  I think we'll want to keep an eye on package sizes and whether including both client and server bloats one or the other excessively as a signal that splitting into multiple modules may be necessary.

**Comment by tigrannajaryan** [comment]
I think we are good with this for now. Closing.
