### ISSUE TITLE
Client should expose the internal sender or provide a method to send async message to the server

### ISSUE THREAD

**Issue by kart** [open-telemetry/opamp-go#45]
Currently, neither the transport sender (`internal.Sender`) or a method that allows for async send to the server is exposed by the client.

As the supervisor is shaping up, I think the client should expose a way to send async messages to the sender. I can think of a few reasons:

1. Report failing health of the agent or worse, termination status of the agent.
2. Report agent restart metrics.
3. Report agent package or addon download progress. This is allowed in the spec, but the client doesn't have enough context to fetch this information and for good reasons, I don' think it should either. Instead, the actual downloader should have the ability to report progress to the server through the client.

**Comment by tigrannajaryan** [comment]
Generally, I do not think we should expose `Sender` directly. If we need to send a message then it should be exposed in the `OpAMPClient` interface, similar to for example `SetEffectiveConfig`. Let's keep `Sender` in internal.

>Report failing health of the agent or worse, termination status of the agent.
>Report agent restart metrics.

I think these are both expected to be reported via own telemetry, so shouldn't be done via OpAMP. What OpAMP message do you want to send for these 2 cases?

>Report agent package or addon download progress.

This should happen in response to the OnAddonsAvailable/OnAgentPackageAvailable callbacks. The AddonSyncer and AgentPackageSyncer are supposed to have the context to report the progress. Are these not sufficient?

**Comment by kart** [comment]
I think you are right. I was thinking that there might be separate telemetry needs from the supervisor -- reporting the up/down stats of the collector, but the spec as it stands today doesn't talk about this at least not in the context of the supervisor. And as to the agent/addon download status, etc, the syncer should be a good place.
