### ISSUE TITLE
Client should send status report on reconnect

### ISSUE THREAD

**Issue by andykellr** [open-telemetry/opamp-go#55]
Currently, the status report message is prepared here in client.Start:

https://github.com/open-telemetry/opamp-go/blob/5255de573f20af81acfb8ab864bfea8d986bbeef/client/clientimpl.go#L109-L113

It then begins runUntilStopped and in runOneCycle it ensures it is connected before entering the ReceiverLoop to receive massages from the server:

https://github.com/open-telemetry/opamp-go/blob/5255de573f20af81acfb8ab864bfea8d986bbeef/client/clientimpl.go#L313-L318

If the connection is closed, it will repeat runOneCycle and reconnect, but after reconnection no status message is sent because no message has been prepared.

In our own agent, the workaround was to call SetAgentDescription in the OnConnect callback, but I think the implementation should be doing this automatically.

**Comment by andykellr** [comment]
Here is the section of the spec regarding the agent sending a status report upon connection. I doesn't specifically address reconnecting, but I think this is implied.

https://github.com/open-telemetry/opamp-spec/blob/410dc86792d6109050e767a1d76de12a5b9f0129/specification.md?plain=1#L485-L491

**Comment by dsvanlani** [comment]
@tigrannajaryan I'm working on a PR for this, but will not have anything to show by this afternoons work group.
