### ISSUE TITLE
Allow the agent User-Agent header to be configurable

### ISSUE THREAD

**Issue by andykellr** [open-telemetry/opamp-go#79]
I would like to be able to control the User-Agent header of the agent when communicating with the management server. Currently this defaults to `Go-http-client/1.1`. It can be useful to identify traffic for logging.

I would propose adding a `UserAgent string` field to `StartSettings` and setting the User-Agent header when we set the Authorization header.

**Comment by tigrannajaryan** [comment]
Sounds good to me.

We currently have `AuthorizationHeader` in the `AuthorizationHeader`. Should we simply allow to specify arbitrary headers and not just these 2?

**Comment by andykellr** [comment]
The other option to specify arbitrary headers is in https://github.com/open-telemetry/opamp-go/pull/81

**Comment by andykellr** [comment]
I prefer the option to supply arbitrary headers.
