### ISSUE TITLE
feature: Own Telemetry Reporting

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opamp-go#9]
Add the ability for the Server to tell the Agent where and how to report its own telemetry.

_Originally posted by @tigrannajaryan in https://github.com/open-telemetry/opamp-go/issues/5#issuecomment-960271496_

**Comment by tigrannajaryan** [comment]
This is now implemented in Go client and server and own metric reporting is used in the example server and agent: https://github.com/open-telemetry/opamp-go/tree/main/internal/examples
